// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUrig_e2AivOwAGa3Yfgi3ueW3h9Xa10',
    appId: '1:856493742927:web:07f4d3e93da7cdf1bc833a',
    messagingSenderId: '856493742927',
    projectId: 'fir-realtimedata-9fab9',
    authDomain: 'fir-realtimedata-9fab9.firebaseapp.com',
    databaseURL: 'https://fir-realtimedata-9fab9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtimedata-9fab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_y-PRBAN6Tru-xRKCMEBNRfwk0rzCrA',
    appId: '1:856493742927:android:d98a59557897ece3bc833a',
    messagingSenderId: '856493742927',
    projectId: 'fir-realtimedata-9fab9',
    databaseURL: 'https://fir-realtimedata-9fab9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtimedata-9fab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl7OfLeNn5exB5VWenCbqdPC2hH4z4NLI',
    appId: '1:856493742927:ios:a8501dec30de442dbc833a',
    messagingSenderId: '856493742927',
    projectId: 'fir-realtimedata-9fab9',
    databaseURL: 'https://fir-realtimedata-9fab9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtimedata-9fab9.firebasestorage.app',
    iosBundleId: 'com.example.janEleventhTrolleyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl7OfLeNn5exB5VWenCbqdPC2hH4z4NLI',
    appId: '1:856493742927:ios:a8501dec30de442dbc833a',
    messagingSenderId: '856493742927',
    projectId: 'fir-realtimedata-9fab9',
    databaseURL: 'https://fir-realtimedata-9fab9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtimedata-9fab9.firebasestorage.app',
    iosBundleId: 'com.example.janEleventhTrolleyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvUrig_e2AivOwAGa3Yfgi3ueW3h9Xa10',
    appId: '1:856493742927:web:07f4d3e93da7cdf1bc833a',
    messagingSenderId: '856493742927',
    projectId: 'fir-realtimedata-9fab9',
    authDomain: 'fir-realtimedata-9fab9.firebaseapp.com',
    databaseURL: 'https://fir-realtimedata-9fab9-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtimedata-9fab9.firebasestorage.app',
  );

}